version: "3"

services:
    heropgsql:
        environment:
            - POSTGRES_DB=practice
            - POSTGRES_USER=hero
            - POSTGRES_PASSWORD=v3ry23C93tp422w0Rd
        image: postgres:12.4-alpine
        hostname: heropgsql
        expose:
            - 5432
        ports:
            - 5432:5432
        container_name: heropgsql
        labels:
            - SERVICE_NAME=heropgsql
        volumes:
            - postgres:/var/lib/postgresql/data

    heropgadmin:
        image: dpage/pgadmin4:4.27
        links:
            - heropgsql
        depends_on:
            - heropgsql
        expose:
            - 5445
        ports:
            - 5445:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=hero@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=v3ry23C93tp422w0Rd

volumes:
    postgres:

